server:
  port: 8095

spring:
  application:
    name: video-inventory-management

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_management_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: D:\Job\Celestial Invention\video-inventory-management\file-storage

white-list: | 
  /video/saveVideo

remove-path: /api/v1/vim