server:
  port: 8095

spring:
  application:
    name: video-inventory-management

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_management_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: true
